"""init

Revision ID: 4a3421b8ad04
Revises: 
Create Date: 2025-07-17 10:18:42.942288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3421b8ad04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aktivitas_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pir1_status', sa.Boolean(), nullable=True),
    sa.Column('pir2_status', sa.Boolean(), nullable=True),
    sa.Column('pir3_status', sa.Boolean(), nullable=True),
    sa.Column('jarak_ultrasonik', sa.Float(), nullable=True),
    sa.Column('tipe_objek', sa.String(length=50), nullable=True),
    sa.Column('buzzer_status', sa.Boolean(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gambar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomor_hp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_hp', sa.String(length=15), nullable=False),
    sa.Column('dibuat_sejak', sa.DateTime(timezone=True), nullable=True),
    sa.Column('diubah_sejak', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_hp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nomor_hp')
    op.drop_table('gambar')
    op.drop_table('aktivitas_sensor')
    # ### end Alembic commands ###
